default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  # Package Manager
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.16
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      - id: uv-sync

  # Linter/Formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.6
    hooks:
      - id: ruff
      - id: ruff-format